import type { ChargingStation, UserLocation } from '../types/gbfs';
import { estimateWalkingMinutes, getDistanceFromLatLonInMeters } from '../utils/distance';

const BASE_URL = '/api/lime';
const LIME_STATIONS_URL = `${BASE_URL}/api/partners/v2/gbfs/paris/station_information`;

/**
 * Réseau officiel des Lime SwapStations & Hubs de recharge Lime à Paris
 * Partenariats officiels Lime (Armoires de batteries swappables Franprix, Hubs Q-Park, Station F et Hub Masséna)
 */
export const BASE_LIME_STATIONS = [
  {
    id: 'lime-hub-massena',
    name: 'Lime Hub Central Paris (Masséna)',
    address: 'Boulevard Masséna / Porte d’Ivry, 75013 Paris',
    lat: 48.829,
    lon: 2.3898,
    operator: 'Lime Operations',
    plugTypes: ['Recharge rapide haute capacité', 'Armoire échange batteries Lime Gen 4 & Lime-E'],
    powerKw: 50,
    hasStandardSocket: true,
    isTwoWheeler: true,
    isLimeHub: true,
  },
  {
    id: 'lime-swap-franprix-gobelins',
    name: 'Lime SwapStation — Franprix Gobelins',
    address: '51 Avenue des Gobelins, 75013 Paris',
    lat: 48.83478,
    lon: 2.35355,
    operator: 'Lime x Franprix',
    plugTypes: ['Armoire échange batterie Lime', 'Libre-service 7j/7', 'Batteries 100% chargées'],
    powerKw: 11,
    hasStandardSocket: false,
    isTwoWheeler: true,
    isLimeHub: false,
  },
  {
    id: 'lime-swap-station-f',
    name: 'Lime SwapStation — Station F',
    address: '55 Boulevard Vincent Auriol, 75013 Paris',
    lat: 48.8349,
    lon: 2.3712,
    operator: 'Lime',
    plugTypes: ['Borne échange automatique batterie Lime', 'Batteries 100% chargées'],
    powerKw: 22,
    hasStandardSocket: false,
    isTwoWheeler: true,
    isLimeHub: false,
  },
  {
    id: 'lime-swap-franprix-rivoli',
    name: 'Lime SwapStation — Franprix Rivoli / Châtelet',
    address: '74 Rue de Rivoli, 75004 Paris',
    lat: 48.8575,
    lon: 2.3514,
    operator: 'Lime x Franprix',
    plugTypes: ['Armoire échange batterie Lime', 'Libre-service 24/7'],
    powerKw: 11,
    hasStandardSocket: false,
    isTwoWheeler: true,
    isLimeHub: false,
  },
  {
    id: 'lime-swap-franprix-rennes',
    name: 'Lime SwapStation — Franprix Saint-Germain / Rennes',
    address: '89 Rue de Rennes, 75006 Paris',
    lat: 48.8512,
    lon: 2.3298,
    operator: 'Lime x Franprix',
    plugTypes: ['Armoire échange batterie Lime', 'Batteries prêtes à l’emploi'],
    powerKw: 11,
    hasStandardSocket: false,
    isTwoWheeler: true,
    isLimeHub: false,
  },
  {
    id: 'lime-swap-franprix-saint-marcel',
    name: 'Lime SwapStation — Franprix Saint-Marcel',
    address: '80 Boulevard Saint-Marcel, 75005 Paris',
    lat: 48.8385,
    lon: 2.3582,
    operator: 'Lime x Franprix',
    plugTypes: ['Armoire échange batterie Lime', 'Libre-service'],
    powerKw: 11,
    hasStandardSocket: false,
    isTwoWheeler: true,
    isLimeHub: false,
  },
  {
    id: 'lime-swap-franprix-monge',
    name: 'Lime SwapStation — Franprix Monge / Quartier Latin',
    address: '55 Rue Monge, 75005 Paris',
    lat: 48.8458,
    lon: 2.3512,
    operator: 'Lime x Franprix',
    plugTypes: ['Armoire échange batterie Lime', 'Échange en 10 secondes'],
    powerKw: 11,
    hasStandardSocket: false,
    isTwoWheeler: true,
    isLimeHub: false,
  },
  {
    id: 'lime-swap-franprix-tolbiac',
    name: 'Lime SwapStation — Franprix Tolbiac',
    address: '135 Rue de Tolbiac, 75013 Paris',
    lat: 48.8262,
    lon: 2.3575,
    operator: 'Lime x Franprix',
    plugTypes: ['Armoire échange batterie Lime', 'Libre-service 7j/7'],
    powerKw: 11,
    hasStandardSocket: false,
    isTwoWheeler: true,
    isLimeHub: false,
  },
  {
    id: 'lime-swap-franprix-glaciere',
    name: 'Lime SwapStation — Franprix Glacière',
    address: '24 Rue de la Glacière, 75013 Paris',
    lat: 48.8329,
    lon: 2.3458,
    operator: 'Lime x Franprix',
    plugTypes: ['Armoire échange batterie Lime', 'Batteries 100% chargées'],
    powerKw: 11,
    hasStandardSocket: false,
    isTwoWheeler: true,
    isLimeHub: false,
  },
  {
    id: 'lime-swap-franprix-voltaire',
    name: 'Lime SwapStation — Franprix République / Voltaire',
    address: '122 Boulevard Voltaire, 75011 Paris',
    lat: 48.8615,
    lon: 2.3765,
    operator: 'Lime x Franprix',
    plugTypes: ['Armoire échange batterie Lime', 'Libre-service'],
    powerKw: 11,
    hasStandardSocket: false,
    isTwoWheeler: true,
    isLimeHub: false,
  },
  {
    id: 'lime-swap-franprix-abbesses',
    name: 'Lime SwapStation — Franprix Montmartre / Abbesses',
    address: '32 Rue des Abbesses, 75018 Paris',
    lat: 48.8847,
    lon: 2.3375,
    operator: 'Lime x Franprix',
    plugTypes: ['Armoire échange batterie Lime', 'Échange en 10 secondes'],
    powerKw: 11,
    hasStandardSocket: false,
    isTwoWheeler: true,
    isLimeHub: false,
  },
  {
    id: 'lime-swap-franprix-saint-lazare',
    name: 'Lime SwapStation — Franprix Saint-Lazare',
    address: '112 Rue Saint-Lazare, 75008 Paris',
    lat: 48.8758,
    lon: 2.3242,
    operator: 'Lime x Franprix',
    plugTypes: ['Armoire échange batterie Lime', 'Batteries 100% chargées'],
    powerKw: 11,
    hasStandardSocket: false,
    isTwoWheeler: true,
    isLimeHub: false,
  },
  {
    id: 'lime-swap-franprix-bastille',
    name: 'Lime SwapStation — Franprix Bastille / Roquette',
    address: '48 Rue de la Roquette, 75011 Paris',
    lat: 48.8542,
    lon: 2.3725,
    operator: 'Lime x Franprix',
    plugTypes: ['Armoire échange batterie Lime', 'Échange en 10 secondes'],
    powerKw: 11,
    hasStandardSocket: false,
    isTwoWheeler: true,
    isLimeHub: false,
  },
  {
    id: 'lime-swap-franprix-bercy',
    name: 'Lime SwapStation — Franprix Gare de Lyon / Bercy',
    address: '14 Rue de Bercy, 75012 Paris',
    lat: 48.8435,
    lon: 2.3735,
    operator: 'Lime x Franprix',
    plugTypes: ['Armoire échange batterie Lime', 'Libre-service'],
    powerKw: 11,
    hasStandardSocket: false,
    isTwoWheeler: true,
    isLimeHub: false,
  },
  {
    id: 'lime-swap-franprix-alesia',
    name: 'Lime SwapStation — Franprix Alésia',
    address: '28 Rue d’Alésia, 75014 Paris',
    lat: 48.8285,
    lon: 2.3325,
    operator: 'Lime x Franprix',
    plugTypes: ['Armoire échange batterie Lime', 'Batteries 100% chargées'],
    powerKw: 11,
    hasStandardSocket: false,
    isTwoWheeler: true,
    isLimeHub: false,
  },
  {
    id: 'lime-swap-franprix-convention',
    name: 'Lime SwapStation — Franprix Convention',
    address: '187 Rue de la Convention, 75015 Paris',
    lat: 48.8378,
    lon: 2.2985,
    operator: 'Lime x Franprix',
    plugTypes: ['Armoire échange batterie Lime', 'Libre-service'],
    powerKw: 11,
    hasStandardSocket: false,
    isTwoWheeler: true,
    isLimeHub: false,
  },
  {
    id: 'lime-hub-qpark-vendome',
    name: 'Lime Charging Hub — Q-Park Vendôme / Opéra',
    address: '28 Place Vendôme, 75001 Paris',
    lat: 48.8679,
    lon: 2.3305,
    operator: 'Lime x Q-Park',
    plugTypes: ['Station de charge rapide Lime', 'Stock batteries prêtes'],
    powerKw: 22,
    hasStandardSocket: true,
    isTwoWheeler: true,
    isLimeHub: true,
  },
  {
    id: 'lime-hub-qpark-etoile',
    name: 'Lime Charging Hub — Q-Park Étoile / Foch',
    address: 'Avenue Foch, 75016 Paris',
    lat: 48.8745,
    lon: 2.2912,
    operator: 'Lime x Q-Park',
    plugTypes: ['Station de charge Lime', 'Zone Juicer & Ops'],
    powerKw: 22,
    hasStandardSocket: true,
    isTwoWheeler: true,
    isLimeHub: true,
  },
  {
    id: 'lime-hub-qpark-montparnasse',
    name: 'Lime Charging Hub — Q-Park Montparnasse',
    address: 'Rue du Commandant Mouchotte, 75014 Paris',
    lat: 48.8398,
    lon: 2.3185,
    operator: 'Lime x Q-Park',
    plugTypes: ['Station de charge Lime', 'Armoire échange batteries'],
    powerKw: 22,
    hasStandardSocket: true,
    isTwoWheeler: true,
    isLimeHub: true,
  },
  {
    id: 'lime-base-pantin',
    name: 'Lime Base Logistique Nord (Pantin)',
    address: 'Rue du Débarcadère, 93500 Pantin',
    lat: 48.8955,
    lon: 2.4045,
    operator: 'Lime Operations',
    plugTypes: ['Atelier maintenance & recharge massive batteries'],
    powerKw: 60,
    hasStandardSocket: true,
    isTwoWheeler: true,
    isLimeHub: true,
  },
  {
    id: 'lime-base-gentilly',
    name: 'Lime Base Logistique Sud (Gentilly)',
    address: 'Avenue Paul Vaillant-Couturier, 94250 Gentilly',
    lat: 48.8165,
    lon: 2.3362,
    operator: 'Lime Operations',
    plugTypes: ['Atelier maintenance & recharge massive batteries'],
    powerKw: 60,
    hasStandardSocket: true,
    isTwoWheeler: true,
    isLimeHub: true,
  },
  {
    id: 'lime-swap-franprix-berger',
    name: 'Lime SwapStation — Franprix Les Halles / Berger',
    address: '35 Rue Berger, 75001 Paris',
    lat: 48.8618,
    lon: 2.34383,
    operator: 'Lime x Franprix',
    plugTypes: ['Armoire échange batterie Lime', 'Casiers SwipBox libre-service'],
    powerKw: 11,
    hasStandardSocket: false,
    isTwoWheeler: true,
    isLimeHub: false,
  },
  {
    id: 'lime-swap-franprix-mail',
    name: 'Lime SwapStation — Franprix Bourse / Sentier',
    address: '9 Rue du Mail, 75002 Paris',
    lat: 48.86661,
    lon: 2.34195,
    operator: 'Lime x Franprix',
    plugTypes: ['Armoire échange batterie Lime', 'Échange en 10 secondes'],
    powerKw: 11,
    hasStandardSocket: false,
    isTwoWheeler: true,
    isLimeHub: false,
  },
  {
    id: 'lime-swap-franprix-stgermain',
    name: 'Lime SwapStation — Franprix Boulevard Saint-Germain',
    address: '106 Boulevard Saint-Germain, 75006 Paris',
    lat: 48.85171,
    lon: 2.34246,
    operator: 'Lime x Franprix',
    plugTypes: ['Armoire échange batterie Lime', 'Libre-service'],
    powerKw: 11,
    hasStandardSocket: false,
    isTwoWheeler: true,
    isLimeHub: false,
  },
  {
    id: 'lime-swap-franprix-herrick',
    name: 'Lime SwapStation — Franprix Champs-Élysées / Myron Herrick',
    address: '9 Avenue Myron Herrick, 75008 Paris',
    lat: 48.87396,
    lon: 2.3099,
    operator: 'Lime x Franprix',
    plugTypes: ['Armoire échange batterie Lime', 'Batteries 100% chargées'],
    powerKw: 11,
    hasStandardSocket: false,
    isTwoWheeler: true,
    isLimeHub: false,
  },
  {
    id: 'lime-swap-franprix-choron',
    name: 'Lime SwapStation — Franprix Cadet / Choron',
    address: '22 Rue Choron, 75009 Paris',
    lat: 48.87776,
    lon: 2.34002,
    operator: 'Lime x Franprix',
    plugTypes: ['Armoire échange batterie Lime', 'Casiers SwipBox libre-service'],
    powerKw: 11,
    hasStandardSocket: false,
    isTwoWheeler: true,
    isLimeHub: false,
  },
  {
    id: 'lime-swap-franprix-maubeuge',
    name: 'Lime SwapStation — Franprix Gare du Nord / Maubeuge',
    address: '60 Rue de Maubeuge, 75009 Paris',
    lat: 48.87885,
    lon: 2.34697,
    operator: 'Lime x Franprix',
    plugTypes: ['Armoire échange batterie Lime', 'Libre-service 7j/7'],
    powerKw: 11,
    hasStandardSocket: false,
    isTwoWheeler: true,
    isLimeHub: false,
  },
  {
    id: 'lime-swap-franprix-vellefaux',
    name: 'Lime SwapStation — Franprix Hôpital Saint-Louis / Vellefaux',
    address: '7 Avenue Claude Vellefaux, 75010 Paris',
    lat: 48.87464,
    lon: 2.37017,
    operator: 'Lime x Franprix',
    plugTypes: ['Armoire échange batterie Lime', 'Échange en 10 secondes'],
    powerKw: 11,
    hasStandardSocket: false,
    isTwoWheeler: true,
    isLimeHub: false,
  },
  {
    id: 'lime-swap-franprix-ecuries',
    name: 'Lime SwapStation — Franprix Petites Écuries',
    address: '7 Rue des Petites Écuries, 75010 Paris',
    lat: 48.87306,
    lon: 2.35344,
    operator: 'Lime x Franprix',
    plugTypes: ['Armoire échange batterie Lime', 'Batteries 100% chargées'],
    powerKw: 11,
    hasStandardSocket: false,
    isTwoWheeler: true,
    isLimeHub: false,
  },
  {
    id: 'lime-swap-franprix-montreuil',
    name: 'Lime SwapStation — Franprix Nation / Montreuil',
    address: '63 Rue de Montreuil, 75011 Paris',
    lat: 48.85061,
    lon: 2.38992,
    operator: 'Lime x Franprix',
    plugTypes: ['Armoire échange batterie Lime', 'Libre-service 7j/7'],
    powerKw: 11,
    hasStandardSocket: false,
    isTwoWheeler: true,
    isLimeHub: false,
  },
  {
    id: 'lime-swap-franprix-servan',
    name: 'Lime SwapStation — Franprix Servan / Père Lachaise',
    address: '65 Rue Servan, 75011 Paris',
    lat: 48.8634,
    lon: 2.38139,
    operator: 'Lime x Franprix',
    plugTypes: ['Armoire échange batterie Lime', 'Casiers SwipBox libre-service'],
    powerKw: 11,
    hasStandardSocket: false,
    isTwoWheeler: true,
    isLimeHub: false,
  },
  {
    id: 'lime-swap-franprix-aligre',
    name: 'Lime SwapStation — Franprix Marché d’Aligre',
    address: '13 bis Place d’Aligre, 75012 Paris',
    lat: 48.8489,
    lon: 2.37832,
    operator: 'Lime x Franprix',
    plugTypes: ['Armoire échange batterie Lime', 'Échange en 10 secondes'],
    powerKw: 11,
    hasStandardSocket: false,
    isTwoWheeler: true,
    isLimeHub: false,
  },
  {
    id: 'lime-swap-franprix-diderot',
    name: 'Lime SwapStation — Franprix Reuilly / Diderot',
    address: '142 Boulevard Diderot, 75012 Paris',
    lat: 48.84754,
    lon: 2.38979,
    operator: 'Lime x Franprix',
    plugTypes: ['Armoire échange batterie Lime', 'Batteries 100% chargées'],
    powerKw: 11,
    hasStandardSocket: false,
    isTwoWheeler: true,
    isLimeHub: false,
  },
  {
    id: 'lime-swap-franprix-stjacques',
    name: 'Lime SwapStation — Franprix Saint-Jacques / Denfert',
    address: '40 Boulevard Saint-Jacques, 75014 Paris',
    lat: 48.83313,
    lon: 2.33751,
    operator: 'Lime x Franprix',
    plugTypes: ['Armoire échange batterie Lime', 'Libre-service'],
    powerKw: 11,
    hasStandardSocket: false,
    isTwoWheeler: true,
    isLimeHub: false,
  },
  {
    id: 'lime-swap-franprix-mottepicquet',
    name: 'Lime SwapStation — Franprix La Motte-Picquet',
    address: '63 Avenue de la Motte-Picquet, 75015 Paris',
    lat: 48.8494,
    lon: 2.29869,
    operator: 'Lime x Franprix',
    plugTypes: ['Armoire échange batterie Lime', 'Casiers SwipBox libre-service'],
    powerKw: 11,
    hasStandardSocket: false,
    isTwoWheeler: true,
    isLimeHub: false,
  },
  {
    id: 'lime-swap-franprix-versailles',
    name: 'Lime SwapStation — Franprix Auteuil / Versailles',
    address: '160 Avenue de Versailles, 75016 Paris',
    lat: 48.84046,
    lon: 2.26415,
    operator: 'Lime x Franprix',
    plugTypes: ['Armoire échange batterie Lime', 'Batteries 100% chargées'],
    powerKw: 11,
    hasStandardSocket: false,
    isTwoWheeler: true,
    isLimeHub: false,
  },
  {
    id: 'lime-swap-franprix-gouvion',
    name: 'Lime SwapStation — Franprix Porte Maillot / Gouvion-Saint-Cyr',
    address: '25 Boulevard Gouvion-Saint-Cyr, 75017 Paris',
    lat: 48.88287,
    lon: 2.2873,
    operator: 'Lime x Franprix',
    plugTypes: ['Armoire échange batterie Lime', 'Échange en 10 secondes'],
    powerKw: 11,
    hasStandardSocket: false,
    isTwoWheeler: true,
    isLimeHub: false,
  },
  {
    id: 'lime-swap-franprix-barbes',
    name: 'Lime SwapStation — Franprix Barbès',
    address: '53 Boulevard Barbès, 75018 Paris',
    lat: 48.88917,
    lon: 2.34939,
    operator: 'Lime x Franprix',
    plugTypes: ['Armoire échange batterie Lime', 'Libre-service 7j/7'],
    powerKw: 11,
    hasStandardSocket: false,
    isTwoWheeler: true,
    isLimeHub: false,
  },
];

export async function fetchChargingStations(userLocation: UserLocation | null): Promise<ChargingStation[]> {
  const stations: ChargingStation[] = BASE_LIME_STATIONS.map((base) => ({
    ...base,
    distanceMeters: null,
    walkingMinutes: null,
  }));

  // GBFS endpoint check
  try {
    const res = await fetch(LIME_STATIONS_URL);
    if (res.ok) {
      const data = await res.json();
      const gbfsStations = data?.data?.stations || [];
      for (const gbfsSt of gbfsStations) {
        if (
          gbfsSt.lat &&
          gbfsSt.lon &&
          !stations.some((s) => Math.abs(s.lat - gbfsSt.lat) < 0.001 && Math.abs(s.lon - gbfsSt.lon) < 0.001)
        ) {
          const id = `lime-gbfs-${gbfsSt.station_id}`;
          stations.push({
            id,
            name: `Lime Hub ${gbfsSt.name || 'Paris'}`,
            address: 'Paris Hub Opérations Lime',
            lat: gbfsSt.lat,
            lon: gbfsSt.lon,
            operator: 'Lime Operations',
            plugTypes: ['Hub recharge officiel Lime'],
            powerKw: 50,
            hasStandardSocket: true,
            isTwoWheeler: true,
            isLimeHub: true,
            distanceMeters: null,
            walkingMinutes: null,
          });
        }
      }
    }
  } catch (err) {
    console.warn('[Lime Charging Stations] GBFS check:', err);
  }

  // Distance & walking time calculations
  const enriched = stations.map((st) => {
    let distanceMeters: number | null = null;
    let walkingMinutes: number | null = null;

    if (userLocation) {
      distanceMeters = getDistanceFromLatLonInMeters(userLocation.lat, userLocation.lon, st.lat, st.lon);
      walkingMinutes = estimateWalkingMinutes(distanceMeters);
    }

    return {
      ...st,
      distanceMeters,
      walkingMinutes,
    };
  });

  if (userLocation) {
    enriched.sort((a, b) => (a.distanceMeters ?? 999999) - (b.distanceMeters ?? 999999));
  }

  return enriched;
}
